[build]
  command = "echo 'No build command'"
  publish = "."

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/on-new-message"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
